sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - stable
branches:
  only:
  - master
before_script:
  - (cargo install mdbook --vers ^0.1.5 || true)
script:
- mdbook build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: book
  on:
    branch: master
